#pragma config(Sensor, dgtl3,  jmp11,          sensorTouch)
#pragma config(Sensor, dgtl4,  jmp12,          sensorTouch)
#pragma config(Motor,  port1,           LeftB,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Arm1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Fork1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Fork2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightB,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightF,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Mech3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Mech4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LeftF,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task auto_(){
motor[LeftB] = vexRT[Ch3];
motor[LeftF] = -vexRT[Ch3];
wait1Msec(1500);
motor[LeftB] = 0;
motor[LeftF] = 0;
wait1Msec(1500);
motor[Arm1] = 127;
motor[Arm2] = -127;
wait1Msec(1500);
motor[Arm1] = 0;
motor[Arm2] = 0;
wait1Msec(1500);
motor[Fork1] = 63;
motor[Fork2] = -63;
wait1Msec(1500);
motor[Fork1] = 0;
motor[Fork2] = 0;
}
task main()
{

	startTask(auto_);
  while(true)
  {

        if(vexRT[Btn6U] == 1)
 				{
 					motor[Arm1] = 127;
 					motor[Arm2] = -127;
 				}
 				else if(vexRT[Btn6D] == 1)
 				{
 					motor[Arm1] = -127;
 					motor[Arm2] = 127;
 				}
 				else
 				{
					motor[Arm1] = 0;
 					motor[Arm2] = 0;
 				}

				if(vexRT[Btn5U] == 1)
 				{
 					motor[Fork1] = 63;
 					motor[Fork2] = -63;
 				}
 				else if(vexRT[Btn5D] == 1)
 				{
 					motor[Fork1] = -63;
 					motor[Fork2] = 63;
 				}
 				else
 				{
					motor[Fork1] = 0;
 					motor[Fork2] = 0;
 				}

      motor[LeftB] = vexRT[Ch3];
			motor[LeftF] = -vexRT[Ch3];
			motor[RightB] = -vexRT[Ch2];
			motor[RightF] = vexRT[Ch2];
    }

}
